### ISSUE TITLE
MUI_PAGE_CUSTOMFUNCTION_*

### ISSUE THREAD

**Issue by afrowuk** [idleberg/sublime-nsis#3]
Thank you very much for this package. I recently ditched Notepad2 in favour of this. One small error I've noticed is when you autocomplete MUI_PAGE_CUSTOMFUNCTION, it autocompletes with !insertmacro instead of !define.

Stu

**Comment by idleberg** [comment]
Thank you! I have to admit, I hardly write NSIS these days, so there might be several more issues like this. But for now it's [these lines](https://github.com/idleberg/sublime-nsis/blob/master/NSIS.sublime-completions#L1051-L1053) that should use `!define`?

**Comment by afrowuk** [comment]
The following should be !define instead of !insertmacro:
MUI_CUSTOMFUNCTION_* (all of them)
MUI_LANGDLL_ALLLANGUAGES
MUI_LANGDLL_ALWAYSSHOW
MUI_LANGDLL_INFO
MUI_LANGDLL_WINDOWTITLE
MUI_WELCOMEFINISHPAGE_CUSTOMFUNCTION_INIT

Also autocompletes when typing ${EndIf} and ${EndUnless} are missing. Haven't noticed any other issues or omissions yet. Thanks!

Stu

**Comment by idleberg** [comment]
Thanks again for reporting, should be fixed in v1.0.2

**Comment by afrowuk** [comment]
Just noticed another autocomplete typo for ${VersionCompare} - it inserts ${StrFilterS} .... Also is there some way it can replace the ${ if you've typed it before autocomplete? For example if you type ${StrFilterS and then autocomplete, you end up with ${${StrFilterS ...

Thanks again.

Stu

**Comment by idleberg** [comment]
I've fixed `${VersionCompare}`.

Regarding the use of non-word characters, I followed the standard set by the default packages that come with Sublime Text. To change this behaviour, you would have to edit all completion rules and tweak the non-word character selector. I don't find that desirable, so I don't have plans to change that.
